name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: |
        # dotnet test --no-build --verbosity normal --configuration Release
        echo "No tests configured yet. Skipping."

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DPManagement.Web
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './DPManagement.Web/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
